language: python
python:
  - '3.7.1'
install:
  - pip install -r requirements.txt
  - echo $SSH_KEY >> $HOME/.ssh/known_hosts
script: ignore
before_deploy:
  - openssl aes-256-cbc -K $encrypted_07e73b98032d_key -iv $encrypted_07e73b98032d_iv
    -in id_rsa.enc -out id_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 id_rsa
  - ssh-add id_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: bash deploy.sh
  on:
    branch: master
before_install:
  - openssl aes-256-cbc -K $encrypted_07e73b98032d_key -iv $encrypted_07e73b98032d_iv
    -in deploy.sh.enc -out deploy.sh -d

