# Generated by Django 2.1.4 on 2018-12-28 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BuyerSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_scanned', models.DateTimeField(blank=True, null=True)),
                ('currently_scanning', models.BooleanField(default=False)),
                ('last_successful_scan', models.DateTimeField(blank=True, null=True)),
                ('next_scheduled_scan', models.DateTimeField(blank=True, null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopville.Buyer')),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('email_address', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('quantity', models.IntegerField(default=1)),
                ('item_page', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('purchased', models.DateField()),
                ('store', models.CharField(choices=[(1, 'AMAZONCA'), (2, 'AMAZONCOM'), (3, 'BESTBUYCA'), (4, 'BESTBUYCOM'), (5, 'LEGOCA'), (6, 'WALMART'), (7, 'EBGAMES')], max_length=2)),
                ('tracking', models.URLField(null=True)),
                ('shipped', models.BooleanField(default=False, null=True)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopville.Buyer')),
            ],
        ),
        migrations.CreateModel(
            name='StoreEmailLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.CharField(choices=[('1', 'AMAZONCA'), ('2', 'AMAZONCOM'), ('3', 'BESTBUYCA'), ('4', 'BESTBUYCOM'), ('5', 'LEGOCA'), ('6', 'WALMART'), ('7', 'EBGAMES')], max_length=2)),
                ('location', models.CharField(max_length=120)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopville.Buyer')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopville.Order'),
        ),
        migrations.AlterUniqueTogether(
            name='storeemaillocation',
            unique_together={('buyer', 'store')},
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('name', 'order')},
        ),
    ]
